services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules 
    networks:
      - app

volumes:
  app:

networks:
  app:
    driver: bridge